M48
; DRILL file {KiCad (6.0.0)} date Mon Feb 21 16:10:14 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-21T16:10:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X1.9249Y-2.6838
X1.9269Y-2.1358
T2
X0.9439Y-2.6174
X0.9451Y-0.6874
X3.2389Y-0.6864
X3.2399Y-2.6174
T0
M30
